version: "3.8"

services:
  app:
    build: .
    ports:
      - "8090:8090"
    networks:
      - student-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: navin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: telusko
    ports:
      - 5433:5432
    networks:
      - student-network
    volumes:
      - postgres-s-data:/var/lib/postgresql/data

networks:
  student-network:
    driver: bridge

volumes:
  postgres-s-data: